micronaut:
  application:
    name: keyManagerREST

endpoints:
  all:
    sensitive: ${HTTP_SENSITIVE:true}
  health:
    enabled: ${HEALTH_ENABLED:true}
    sensitive: ${HEALTH_SENSITIVE:false}
    details-visible: ${HEALTH_DETAILS_VISIBLE:ANONYMOUS}

grpc:
  client:
    plaintext: ${GRPC_CLIENT_PLAINTEXT:true}
    max-retry-attempts: ${GRPC_CLIENT_RETRY_ATTEMPTS:10}
  channels:
    pixKeyManager:
      address: ${PIX_KEY_MANAGER_URL:`localhost:50051`}