micronaut:
  application:
    name: keyManagerREST

grpc:
  client:
    plaintext: ${GRPC_CLIENT_PLAINTEXT:true}
    max-retry-attempts: ${GRPC_CLIENT_RETRY_ATTEMPTS:10}
  channels:
    pixKeyManager:
      address: ${PIX_KEY_MANAGER_URL:`localhost:50051`}